package com.example.pizza_shop_api.login_and_register;


import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import java.util.Optional;

@Controller // This means that this class is a Controller
@RequestMapping(path="/pizza") // This means URL's start with /pizza (after Application path)
@CrossOrigin(origins = "*") //  allows other application outside this project to communicate with backend
public class LoginController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    @PostMapping(path="/add")
    public @ResponseBody String addNewUser (@RequestParam String userName, @RequestParam int password) {
        Optional<UserService> existingUser = userRepository.findByUserName(userName);
        if (existingUser.isPresent()) {
            return "User already exists";
        } else {
            UserService newUser = new UserService();
            newUser.setUserName(userName);
            newUser.setPassword(password);
            userRepository.save(newUser);
            return "User saved";
        }
    }


    @GetMapping(path="/all")
    public @ResponseBody Iterable<UserService> getAllUsers() {
        // This returns a JSON or XML with the users
        return userRepository.findAll();
    }

    @GetMapping(path="/user")
    public @ResponseBody String getUser(String user, int password){
        UserService userService = new UserService();
        userService.setUserName(user);
        userService.setPassword(password);
        return userService.getUserName();
    }
}